### ISSUE TITLE
No software license for datacite-metadata-generator

### ISSUE THREAD

**Issue by ioverka** [mpaluch/datacite-metadata-generator#1]
Dear Marcin,

thanks a lot for sharing the datacite-metadata-generator. Your solution comes without a software license - was this done on purpose? 

We would like to reuse it on one of our servers, see https://test.doi.mpdl.mpg.de/doxi/md_generator.html - and added an attribution to the footer of the page. Is that okay for you?

Greetings from Munich,
inga

**Comment by mpaluch** [comment]
Hi, your usage is okay with me. This was intended to be fully open source, just please leave the original comment header intact and attribute it to the original source. Thanks.
