### ISSUE TITLE
DataCite Metadata Schema 4.0

### ISSUE THREAD

**Issue by ioverka** [mpaluch/datacite-metadata-generator#2]
Hello again,

do you consider to update the datacite-metadata-generator to the newly released schema version 4.0 (see https://schema.labs.datacite.org/meta/kernel-4.0/) - or is that out of scope?

thanks & greetings,
inga

**Comment by mpaluch** [comment]
Yes the generator will be updated to version 4.0 of the schema but right now I have no timeline for it.

**Comment by mpaluch** [comment]
The generator has been updated to version 4.0.
