### ISSUE TITLE
ResourceType elements with attribute but without value

### ISSUE THREAD

**Issue by ioverka** [mpaluch/datacite-metadata-generator#5]
According to the Datacite Metadata Schema v 4.0 it is fine to create an resourceType element without value, e.g. `<resourceType resourceTypeGeneral="Dataset"/>`. This is currently not supported by the datacite metadata generator.

**Comment by mpaluch** [comment]
Updated ResourceType tag to allow empty values.

**Comment by ioverka** [comment]
thank you!
